version: "3.7"

services:
  proxy:
    container_name: proxy
    hostname: proxy
    domainname: proxy.com
    build:
      context: proxy
      dockerfile: Dockerfile
    ports:
      - "8080:80/tcp"
    networks:
      api_net:
        ipv4_address: 172.16.1.2

  apiserver:
    container_name: apiserver
    hostname: apiserver
    domainname: apiserver.com
    build:
      context: apiserver
      dockerfile: Dockerfile
    # ports:
    #   - "8080:80/tcp"
    networks:
      api_net:
        ipv4_address: 172.16.1.3

networks:
  api_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.1.0/24"
